sudo: false
language: node_js
node_js:
  - "5.4"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - npm i -g npm@^3.3.0
  - npm install -g bower
  - npm install
  - bower install
script: node server.js
